const menu = [
  {
    id: 1,
    title: 'Classic Fries',
    category: 'Potato Family',
    price: 59,
    preference : 1,
  },
  {
    id: 2,
    title: 'Peri Peri Fries',
    category: 'Potato Family',
    price: 69,
    preference : 1,
  },
  {
    id: 3,
    title: 'Cheese Fries',
    category: 'Potato Family',
    price: 79,
    preference : 1,
  },
  {
    id: 4,
    title: 'Veg Cutlet',
    category: 'Potato Family',
    price: 39,
    preference : 1,
  },
  {
    id: 5,
    title: 'Cheese Ball',
    category: 'Potato Family',
    price: 69,
    preference : 1,
  },
  {
    id: 6,
    title: 'Cheese corn triangle',
    category: 'Potato Family',
    price: 79,
    preference : 1,
  },
  {
    id: 7,
    title: 'Aloo Kabab',
    category: 'Potato Family',
    price: 69,
    preference : 1,
  },
  // maggie
  {
    id: 8,
    title: 'Masala Maggie',
    category: 'Maggie',
    price: 49,
    preference : 1,
  },
  {
    id: 9,
    title: 'Cheese Maggie',
    category: 'Maggie',
    price: 59,
    preference : 1,
  },
  {
    id: 10,
    title: 'Paneer and corn Maggie',
    category: 'Maggie',
    price: 59,
    preference : 1,
  },
  // pasta paradise
  {
    id: 11,
    title: 'White Sauce Pasta',
    category: 'Pasta Paradise',
    price: 119,
    preference : 1,
  },
  {
    id: 12,
    title: 'Red Sauce Pasta',
    category: 'Pasta Paradise',
    price: 119,
    preference : 1,
  },
  {
    id: 13,
    title: 'Mixed Sauce Pasta',
    category: 'Pasta Paradise',
    price: 129,
    preference : 1,
  },
  // sandwich
  {
    id: 14,
    title: 'Veg busted grill',
    category: 'Sandwiches',
    price: 69,
    preference : 1,
  },
  {
    id: 15,
    title: 'Cheesy paneer grill',
    category: 'Sandwiches',
    price: 79,
    preference : 1,
  },
  {
    id: 16,
    title: 'Cheesy corn',
    category: 'Sandwiches',
    price: 69,
    preference : 1,
  },
  {
    id: 17,
    title: 'Chef special sandwich',
    category: 'Sandwiches',
    price: 79,
    preference : 1,
  },
  // burger feast
  {
    id: 18,
    title: 'Veg cheese loaded',
    category: 'Burger Feast',
    price: 69,
    preference : 1,
  },
  {
    id: 19,
    title: 'Aloo tikki',
    category: 'Burger Feast',
    price: 69,
    preference : 1,
  },
  {
    id: 20,
    title: 'Crispy paneer patty',
    category: 'Burger Feast',
    price: 79,
    preference : 1,
  },
  {
    id: 21,
    title: 'Chicken Burger',
    category: 'Burger Feast',
    price: 89,
    preference : 1,
  },
  // pizza club
  {
    id: 22,
    title: 'Paneer Lovers',
    category: 'Pizza Club',
    price: 129,
    preference : 1,
  },
  {
    id: 23,
    title: 'Cheesy Mushroom',
    category: 'Pizza Club',
    price: 129,
    preference : 1,
  },
  {
    id: 24,
    title: 'Golden Corn Margarita',
    category: 'Pizza Club',
    price: 119,
    preference : 1,
  },
  {
    id: 25,
    title: 'Buzz Club Loaded',
    category: 'Pizza Club',
    price: 149,
    preference : 1,
  },
  {
    id: 26,
    title: 'Chicken Pizza',
    category: 'Pizza Club',
    price: 149,
    preference : 0,
  },
  {
    id: 27,
    title: 'Chicken Peri Peri Pizza',
    category: 'Pizza Club',
    price: 169,
    preference : 0,
  },
  // momo club
  {
    id: 28,
    title: 'Veg Steam Momo',
    category: 'Momo Club',
    price: 59,
    preference : 1,
  },
  {
    id: 29,
    title: 'Veg Fried Momo',
    category: 'Momo Club',
    price: 69,
    preference : 1,
  },
  {
    id: 30,
    title: 'Paneer Steam Momo',
    category: 'Momo Club',
    price: 69,
    preference : 1,
  },
  {
    id: 31,
    title: 'Paneer Fried Momo',
    category: 'Momo Club',
    price: 79,
    preference : 1,
  },
  {
    id: 32,
    title: 'Momos Manchurian',
    category: 'Momo Club',
    price: 79,
    preference : 1,
  },
  {
    id: 33,
    title: 'Chilly Momos',
    category: 'Momo Club',
    price: 79,
    preference : 1,
  },
  {
    id: 34,
    title: 'Peri Peri Momos',
    category: 'Momo Club',
    price: 79,
    preference : 1,
  },
  {
    id: 35,
    title: 'Chicken Steam Momos',
    category: 'Momo Club',
    price: 79,
    preference : 0,
  },
  {
    id: 36,
    title: 'Chicken Fried Momos',
    category: 'Momo Club',
    price: 89,
    preference : 0,
  },
  // rolls
  {
    id: 37,
    title: 'Veg Roll',
    category: 'Rolls',
    price: 59,
    preference : 1,
  },
  {
    id: 38,
    title: 'Paneer Roll',
    category: 'Rolls',
    price: 69,
    preference : 1,
  },
  {
    id: 39,
    title: 'Chicken Roll',
    category: 'Rolls',
    price: 79,
    preference : 0,
  },
  {
    id: 40,
    title: 'Egg Roll',
    category: 'Rolls',
    price: 69,
    preference : 0,
  },
  // starters
  {
    id: 41,
    title: 'Gobi 65',
    category: 'Starters',
    price: 59,
    preference : 1,
  },
  {
    id: 42,
    title: 'Gobi Manchurian',
    category: 'Starters',
    price: 69,
    preference : 1,
  },
  {
    id: 43,
    title: 'Gobi Chilly',
    category: 'Starters',
    price: 79,
    preference : 1,
  },
  {
    id: 44,
    title: 'Babycorn 65',
    category: 'Starters',
    price: 69,
    preference : 1,
  },
  {
    id: 45,
    title: 'Babycorn Manchurian',
    category: 'Starters',
    price: 79,
    preference : 1,
  },
  {
    id: 46,
    title: 'Babycorn Chilly',
    category: 'Starters',
    price: 89,
    preference : 1,
  },
  {
    id: 47,
    title: 'Mushroom 65',
    category: 'Starters',
    price: 69,
    preference : 1,
  },
  {
    id: 48,
    title: 'Mushroom Manchurian',
    category: 'Starters',
    price: 79,
    preference : 1,
  },
  {
    id: 49,
    title: 'Mushroom Chilly',
    category: 'Starters',
    price: 89,
    preference : 1,
  },
  {
    id: 50,
    title: 'Paneer 65',
    category: 'Starters',
    price: 79,
    preference : 1,
  },
  {
    id: 51,
    title: 'Paneer Manchurian',
    category: 'Starters',
    price: 89,
    preference : 1,
  },
  {
    id: 52,
    title: 'Paneer Chilly',
    category: 'Starters',
    price: 89,
    preference : 1,
  },
  {
    id: 53,
    title: 'Chicken Popcorn',
    category: 'Starters',
    price: 89,
    preference : 0,
  },
  {
    id: 54,
    title: 'Peri Peri Chicken Strip',
    category: 'Starters',
    price: 99,
    preference : 0,
  },
  {
    id: 55,
    title: 'Chicken Kabab',
    category: 'Starters',
    price: 109,
    preference : 0,
  },
  {
    id: 56,
    title: 'Crispy Chicken',
    category: 'Starters',
    price: 119,
    preference : 0,
  },
  {
    id: 57,
    title: 'Chicken Lollypop',
    category: 'Starters',
    price: 129,
    preference : 0,
  },
  {
    id: 58,
    title: 'Chilly Chicken',
    category: 'Starters',
    price: 129,
    preference : 0,
  },
  {
    id: 59,
    title: 'Chicken Manchurian',
    category: 'Starters',
    price: 129,
    preference : 0,
  },
  {
    id: 60,
    title: 'Lemon Chicken',
    category: 'Starters',
    price: 129,
    preference : 0,
  },
  {
    id: 61,
    title: 'Pepper Chicken',
    category: 'Starters',
    price: 129,
    preference : 0,
  },
  {
    id: 62,
    title: 'Guntur Chicken',
    category: 'Starters',
    price: 139,
    preference : 0,
  },
  {
    id: 63,
    title: 'Chicken Liver Fry',
    category: 'Starters',
    price: 109,
    preference : 0,
  },
  {
    id: 64,
    title: 'Dragon Chicken',
    category: 'Starters',
    price: 159,
    preference : 0,
  },
  {
    id: 65,
    title: 'Japanese Chicken',
    category: 'Starters',
    price: 159,
    preference : 0,
  },
  {
    id: 66,
    title: 'Buzz Club Spl Chicken',
    category: 'Starters',
    price: 149,
    preference : 0,
  },
  {
    id: 67,
    title: 'Drums of Heaven',
    category: 'Starters',
    price: 149,
    preference : 0,
  },
  {
    id: 68,
    title: 'Chicken Ghee Roast',
    category: 'Starters',
    price: 159,
    preference : 0,
  },
  {
    id: 69,
    title: 'Egg Chilly',
    category: 'Starters',
    price: 109,
    preference : 0,
  },
  {
    id: 70,
    title: 'Egg Manchurian',
    category: 'Starters',
    price: 109,
    preference : 0,
  },
  {
    id: 71,
    title: 'Egg French',
    category: 'Starters',
    price: 99,
    preference : 0,
  },
  {
    id: 72,
    title: 'Egg Double Omelet',
    category: 'Starters',
    price: 59,
    preference : 0,
  },
  {
    id: 73,
    title: 'Egg Burji',
    category: 'Starters',
    price: 79,
    preference : 0,
  },
  {
    id: 74,
    title: 'Egg kabab',
    category: 'Starters',
    price: 89,
    preference : 0,
  },
  {
    id: 75,
    title: 'Egg Gobi',
    category: 'Starters',
    price: 89,
    preference : 0,
  },
  // noodles family
  {
    id: 76,
    title: 'Veg Noodles',
    category: 'Noodles Family',
    price: 69,
    preference : 1,
  },
  {
    id: 77,
    title: 'Chilly Garlic Noodles',
    category: 'Noodles Family',
    price: 79,
    preference : 1,
  },
  {
    id: 78,
    title: 'Schezwan Noodles',
    category: 'Noodles Family',
    price: 89,
    preference : 1,
  },
  {
    id: 79,
    title: 'Mushroom Mix Noodles',
    category: 'Noodles Family',
    price: 89,
    preference : 1,
  },
  {
    id: 80,
    title: 'Paneer Mix Noodles',
    category: 'Noodles Family',
    price: 89,
    preference : 1,
  },
  {
    id: 81,
    title: 'Gobi Mix Noodles',
    category: 'Noodles Family',
    price: 79,
    preference : 1,
  },
  {
    id: 82,
    title: 'Egg Noodles',
    category: 'Noodles Family',
    price: 89,
    preference : 0,
  },
  {
    id: 83,
    title: 'Chicken Noodles',
    category: 'Noodles Family',
    price: 109,
    preference : 0,
  },
  // rice family
  {
    id: 84,
    title: 'Veg Fried Rice',
    category: 'Rice Family',
    price: 69,
    preference : 1,
  },
  {
    id: 85,
    title: 'Paneer Fried Rice',
    category: 'Rice Family',
    price: 79,
    preference : 1,
  },
  {
    id: 86,
    title: 'Mushroom Fried Rice',
    category: 'Rice Family',
    price: 79,
    preference : 1,
  },
  {
    id: 87,
    title: 'Schezwan Fried Rice',
    category: 'Rice Family',
    price: 89,
    preference : 1,
  },
  {
    id: 88,
    title: 'Egg Fried Rice',
    category: 'Rice Family',
    price: 79,
    preference : 0,
  },
  {
    id: 89,
    title: 'Chicken Fried Rice',
    category: 'Rice Family',
    price: 99,
    preference : 0,
  },
  // milkshakes
  {
    id: 90,
    title: 'Cold Coffee',
    category: 'Milkshakes',
    price: 59,
    preference : 1,
  },
  {
    id: 91,
    title: 'Chikoo Milkshake',
    category: 'Milkshakes',
    price: 69,
    preference : 1,
  },
  {
    id: 92,
    title: 'Oreo Milkshake',
    category: 'Milkshakes',
    price: 79,
    preference : 1,
  },
  {
    id: 93,
    title: 'Kitkat Milkshake',
    category: 'Milkshakes',
    price: 79,
    preference : 1,
  },
  // sweet blend
  {
    id: 94,
    title: 'Chocolate blend',
    category: 'Sweet Blend',
    price: 99,
    preference : 1,
  },
  {
    id: 95,
    title: 'Oreo blend',
    category: 'Sweet Blend',
    price: 99,
    preference : 1,
  },
  // mojito
  {
    id: 96,
    title: 'Lemon Soda',
    category: 'Mojito',
    price: 39,
    preference : 1,
  },
  {
    id: 97,
    title: 'Lemon Mojito',
    category: 'Mojito',
    price: 69,
    preference : 1,
  },
  {
    id: 98,
    title: 'Virgin Mojito',
    category: 'Mojito',
    price: 69,
    preference : 1,
  },
  {
    id: 99,
    title: 'Watermelon Mojito',
    category: 'Mojito',
    price: 79,
    preference : 1,
  },
  {
    id: 100,
    title: 'Blueberry Mojito',
    category: 'Mojito',
    price: 79,
    preference : 1,
  },
  {
    id: 101,
    title: 'Kiwi Mojito',
    category: 'Mojito',
    price: 89,
    preference : 1,
  },
  // icecreams
  {
    id: 102,
    title: 'Vanilla',
    category: 'Ice-Creams',
    price: 39,
    preference : 1,
  },
  {
    id: 103,
    title: 'Chocoloate',
    category: 'Ice-Creams',
    price: 49,
    preference : 1,
  },
  {
    id: 104,
    title: 'Mango',
    category: 'Ice-Creams',
    price: 49,
    preference : 1,
  },
  {
    id: 105,
    title: 'ButterScotch',
    category: 'Ice-Creams',
    price: 59,
    preference : 1,
  },
  {
    id: 106,
    title: 'BlackCurrent',
    category: 'Ice-Creams',
    price: 59,
    preference : 1,
  },
  // combos
  {
    id: 107,
    title: 'Classic fries + Steam Momo + Ice cream',
    category: 'Combos',
    price: 139,
    preference : 1,
  },
  {
    id: 108,
    title: 'Paneer sandwich + Gobi Manchurian + Oreo milkshake',
    category: 'Combos',
    price: 179,
    preference : 1,
  },
  {
    id: 109,
    title: 'Aloo Kabab + Oreo Blend + Paneer Fried rice',
    category: 'Combos',
    price: 209,
    preference : 1,
  },
  {
    id: 110,
    title: 'Blueberry Mojito + White sauce pasta + Corn pizza',
    category: 'Combos',
    price: 279,
    preference : 1,
  },
  {
    id: 111,
    title: 'Egg Fried Rice + Egg Chilly + Lemon Mojito',
    category: 'Combos',
    price: 199,
    preference : 0,
  },
  {
    id: 112,
    title: 'Egg Noodles + 2 Egg Kabab + Ice-cream',
    category: 'Combos',
    price: 119,
    preference : 0,
  },
  {
    id: 113,
    title: 'Chicken Fried Rice + Chilly Chicken + Lemon Mojito',
    category: 'Combos',
    price: 279,
    preference : 0,
  },
  {
    id: 114,
    title: 'Chicken Noodles + 2 pc. Kabab + Lemon Soda',
    category: 'Combos',
    price: 149,
    preference : 0,
  },




];
export default menu;
